@localhost=localhost:4004/odata/v4/main
@id=60d12011-2b25-48c2-a2e2-962f826b9f73

GET http://{{localhost}}/Customers
Content-Type: application/json 

###

POST http://{{localhost}}/Customers
Content-Type: application/json 

{
    "id": "{{id}}",
    "firstName": "Maique",
    "lastName": "Lima",
    "email": "maique.lima@moovi.com"
}

#---------------------------------------
# entity Customers {
#     key id: UUID;
#         firstName: String(20);
#         lastName: String(100);
#         email: String(255);
# }
#---------------------------------------

###

PUT http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json 

{ 
    "firstName": "Robert"
}


###

GET http://{{localhost}}/Customers?$filter=endswith(firstName,'-27700650')
Content-Type: application/json 

###

# Buscando dados com o $Search

GET http://{{localhost}}/Customers?$search=firstName
Content-Type: application/json 

###

