@localhost=localhost:4004/odata/v4/main

@id=4400da51-f63b-4922-8d0b-c112cc7d88d4

@customerId=60d12011-2b25-48c2-a2e2-962f826b9f73

@productId=f0718834-471e-4099-b1ff-0b6f9705a5d7



GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json 

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json 

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "items": [
        {
            "id": "5512fc13-163b-4b02-b8f3-ba729b62c711",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "b3f56618-86e8-4501-ae00-0f707c696bc7",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE  http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json 

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json 

{}


###

#Buscar todos os pedidos maiores ou iguais a 2 milhoes
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000
Content-Type: application/json 

###

#Buscar todos os pedidos menores ou iguais a 200k
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 4397300542693
Content-Type: application/json 

###

#Expadindo os itens
GET http://{{localhost}}/SalesOrderHeaders?$expand=items,customer
Content-Type: application/json 

###

#Expadindo os produtos dentro dos itens - Necessario ser uma associação ou composicao entre os dois
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer
Content-Type: application/json 

###

#Uso do & para combinar filtros
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 20000&$expand=items($expand=product),customer
Content-Type: application/json 

###

#Expadindo os produtos dentro dos itens com filtros
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 20000&$expand=items($expand=product;$filter=quantity le 30),customer
Content-Type: application/json 

###

#Selecionar somente customer e id do sales order header
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=email)
Content-Type: application/json 

###

#Descobrindo quantidade de registros totais
GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json 

###

#Paginando os registros ( Skip / Top )
GET http://{{localhost}}/SalesOrderHeaders?$skip=9&$top=5
Content-Type: application/json 

###

#Buscando dados com o $Search - Utilizando para todos os campos de VARCHAR, TEXT, STRING
GET http://{{localhost}}/SalesOrderHeaders?$search=3l2uz
Content-Type: application/json

###

#Buscando dados com o $Search com filter
GET http://{{localhost}}/SalesOrderHeaders?$search=3l2uz&$filter=totalAmount ge 20000
Content-Type: application/json

###